
const translations = {
    en: {
        home: "Home",
        feature: "feature",
        maintenance: "Maintenance",
        feedback: "Feedback",
        build_websites: "We build powerful websites",
        unlock_power: "Unlock the most powerful websites for business with 100,000+ people globally",
        easy_build: "Easy build powerful websites",
        modern_websites: "Our team is creating modern websites for your webshop, business in days",
        unlock_access: "Unlock Access",
        easy_build_most: "Easy build most powerful websites",
        modern_websites_2: "Our team is creating modern websites for your webshop, business in days",
        unlock_access_2: "Unlock Access",
        easy_build_strategies: "Easy build powerful strategies",
        modern_websites_3: "Our team is creating modern websites for your webshop, business in days",
        unlock_access_3: "Unlock Access",
        basic: "Basic",
        basic_price: "$9.99/month",
        per_site: "per month",
        simple_design: "Simple Design and Layout",
        home_page: "Home Page",
        contact_form: "Contact Form",
        responsive_design: "Responsive Design",
        basic_seo: "Basic SEO Setup",
        get_started: "Get started",
        pro: "Pro",
        pro_price: "$17.99/month",
        all_basic: "All from Basic version",
        advanced_design: "Advanced Design",
        content_management: "Content Management System",
        social_media: "Social Media Integration",
        enhanced_seo: "Enhanced SEO Keysearch",
        premium: "Premium",
        premium_price: "$25.99/month",
        all_pro: "All from Pro",
        ecommerce: "E_commerce Functionality",
        advanced_analytics: "Advanced Analytics",
        blog_setup: "Blog Setup and Integration",
        custom_graphics: "Custom Graphics and Branding",
        website_maintenance: "Website Maintenance",
        get_site_plan: "Get site plan",
        ultra: "Ultra",
        ultra_price: "$32.99/month",
        all_premium: "All from Premium",
        additional_pages: "Additional Pages",
        content_creation: "Content Creation",
        email_newsletter: "Email Newsletter Setup",
        multilingual_support: "Multilingual Support",
        ongoing_maintenance: "Ongoing Maintenance",
        custom_development: "Custom Development",
        faq_quastion_1: "How does it work?",
        faq_quastion_2: "Which plan should I choose?",
        faq_quastion_3: "What markets are supported",
        faq_quastion_4: "Does it work on MetaTrader 4/5?",
        faq_quastion_5: "Can I win every trade using this?",
        faq_quastion_6: "How do discounts work?",
        faq_quastion_7: "Is this friendly for beginners?",
        faq_quastion_8: "Can I change my plan anytime?",
        faq_answer_1: "Once you sign up to a plan above, you'll be brought to a page which gives you instant access. Alink will also beemailed to you in case you miss it.You'll be prompted to connect your TradingView & Discord accounts which are both free platformsthat our tools functionon.We do not store payment credentials, they are encrypted and passed to Stripe & PayPal for a safe& secure way topurchase subscriptions on our site.",
        faq_answer_2: "The Premium Plan is the most popular choice since it works for any trading style and includesthe full set of ourSignals & Overlays™, Oscillator Matrix™, and Price Action Concepts™ toolkits.Choose the Essential Plan for features like support/resistance, trend lines, patterns and more.This plan is also greatfor serious traders who want to speed up their analysis with just our Price Action Concepts™toolkit.Choose the Ultimate Plan if you're a data-driven trader looking to utilize our BacktestingSystem™. It has 3 backtestersthat allow you to backtest all of our toolkits.",
        faq_answer_3: "All of our indicators function on any market available on TradingView such as stocks, crypto,forex, and commodities onall timeframes including 1m, 5m, 15m, 1h, 4H, 1D, etc.The toolkits we provide on every plan can hypothetically fit any style of trading (scalping,swing trading, investing,etc) for finding technical insights.",
        faq_answer_4: "Our paid plans with our exclusive toolkits available above work only on TradingView (freeweb-based charting platform)and you can trade on any platform in real-time based on those charts.We do offer some free tools for MetaTrader 4/5, however, our exclusive toolkits specificallywork on TradingView.",
        faq_answer_5: "Absolutely not. There is no indicator, algorithm, system, or strategy to give you the power topredict markets with aguaranteed % accuracy.We are the largest provider of indicators (free & paid); however, our tools cannot guarantee youmake profits by justfollowing them blindly.We do not recommend blindly following any tool. Trading itself is risky and past performancedoes not guarantee futureresults.",
        faq_answer_6: "For special limited time offers we may have, you can apply the coupon code during checkout if itis not alreadyautomatically applied.Do note all coupons are for the first payment of your subscription only and will not work duringthe process ofupgrading or downgrading. You can always get up to 50% off the total price you'd pay monthly bychoosing to pay annuallyon our plans above.",
        faq_answer_7: "Yes, our Essential & Premium plans are great for beginners.Every plan comes with many tutorials as well as access to our highly active community whereusers can get 24/7 support,discuss strategies, & go through daily analysis amongst each other using LuxAlgo.Our Ultimate Plan was specifically designed for data-driven traders who want to do more advancedbacktesting.",
        faq_answer_8: "Yes, you can upgrade, downgrade, or even extend your plan any time by using our pricing pageonce logged in.For upgrades, we convert remaining time into a value of days on your new plan. For downgrades,your new plan will startonce your current plan ends. For extensions of your current plan, you can only extend yearlysubscriptions and up to 3times which is typically popular during special sales.",


    },
    nl: {
        home: "Home",
        feature: "feature",
        maintenance: "Onderhoud",
        feedback: "Feedback",
        build_websites: "We bouwen krachtige websites",
        unlock_power: "Ontgrendel de krachtigste websites voor bedrijven met 100.000+ mensen wereldwijd",
        easy_build: "Gemakkelijk krachtige websites bouwen",
        modern_websites: "Ons team maakt moderne websites voor uw webshop, bedrijf in dagen",
        unlock_access: "Ontgrendellen",
        easy_build_most: "Gemakkelijk de krachtigste websites bouwen",
        modern_websites_2: "Ons team maakt moderne websites voor uw webshop, bedrijf in dagen",
        unlock_access_2: "Ontgrendellen",
        easy_build_strategies: "Gemakkelijk krachtige strategieën bouwen",
        modern_websites_3: "Ons team maakt moderne websites voor uw webshop, bedrijf in dagen",
        unlock_access_3: "Ontgrendellen",
        basic: "Basis",
        basic_price: "€9.99/maand",
        per_site: "per maand",
        simple_design: "Eenvoudig ontwerp en layout",
        home_page: "Startpagina",
        contact_form: "Contactformulier",
        responsive_design: "Responsief ontwerp",
        basic_seo: "Basis SEO_instelling",
        get_started: "begin",
        pro: "Pro",
        pro_price: "€17.99/maand",
        all_basic: "Alles van Basisversie",
        advanced_design: "Geavanceerd ontwerp",
        content_management: "Content Management Systeem",
        social_media: "Social media_integratie",
        enhanced_seo: "Verbeterde SEO_sleutelzoektocht",
        premium: "Premium",
        premium_price: "€25.99/maand",
        all_pro: "Alles van Pro",
        ecommerce: "E_commerce functionaliteit",
        advanced_analytics: "Geavanceerde analyse",
        blog_setup: "Blogopzet en integratie",
        custom_graphics: "Aangepaste grafische afbeeldingen en branding",
        website_maintenance: "Website onderhoud",
        get_site_plan: "begin",
        ultra: "Ultra",
        ultra_price: "€32.99/maand",
        all_premium: "Alles van Premium",
        additional_pages: "Extra pagina's",
        content_creation: "Contentcreatie",
        email_newsletter: "E_mailnieuwsbrief opzetten",
        multilingual_support: "Meertalige ondersteuning",
        ongoing_maintenance: "Voortdurend onderhoud",
        custom_development: "Aangepaste ontwikkeling",
        faq_quastion_1: "Hoe werkt het?",
        faq_quastion_2: "Welk plan moet ik kiezen?",
        faq_quastion_3: "Welke markten worden ondersteund?",
        faq_quastion_4: "Werkt het op MetaTrader 4/5?",
        faq_quastion_5: "Kan ik elke trade winnen met dit systeem?",
        faq_quastion_6: "Hoe werken kortingen?",
        faq_quastion_7: "Is dit geschikt voor beginners?",
        faq_quastion_8: "Kan ik mijn plan op elk moment wijzigen?",
        faq_answer_1: "Zodra je je hebt aangemeld voor een plan, word je doorgestuurd naar een pagina die je directe toegang geeft. Er wordt ook een link naar je gemaild voor het geval je deze mist. Je wordt gevraagd om je TradingView- en Discord-accounts te koppelen, beide gratis platforms waarop onze tools functioneren. We slaan geen betalingsgegevens op; deze worden versleuteld en doorgegeven aan Stripe & PayPal voor een veilige manier om abonnementen op onze site aan te schaffen.",
        faq_answer_2: "Het Premium Plan is de meest populaire keuze omdat het werkt voor elke handelsstijl en de volledige set van onze Signals & Overlays™, Oscillator Matrix™ en Price Action Concepts™ toolkits bevat. Kies het Essential Plan voor functies zoals ondersteuning/weerstand, trendlijnen, patronen en meer. Dit plan is ook geweldig voor serieuze traders die hun analyse willen versnellen met alleen onze Price Action Concepts™ toolkit. Kies het Ultimate Plan als je een data-gedreven trader bent die gebruik wil maken van ons Backtesting System™. Het heeft 3 backtesters waarmee je al onze toolkits kunt backtesten.",
        faq_answer_3: "Al onze indicatoren werken op elke markt die beschikbaar is op TradingView, zoals aandelen, crypto, forex en grondstoffen op alle tijdframes, waaronder 1m, 5m, 15m, 1h, 4H, 1D, enz. De toolkits die we bij elk plan aanbieden, passen hypothetisch bij elke handelsstijl (scalping, swing trading, beleggen, enz.) om technische inzichten te vinden.",
        faq_answer_4: "Onze betaalde plannen met onze exclusieve toolkits werken alleen op TradingView (gratis webgebaseerd charting platform) en je kunt in real-time handelen op elk platform op basis van die grafieken. We bieden enkele gratis tools aan voor MetaTrader 4/5, maar onze exclusieve toolkits werken specifiek op TradingView.",
        faq_answer_5: "Absoluut niet. Er is geen indicator, algoritme, systeem of strategie die je de kracht kan geven om markten te voorspellen met een gegarandeerde nauwkeurigheid. We zijn de grootste aanbieder van indicatoren (gratis & betaald); echter, onze tools kunnen je niet garanderen dat je winst maakt door ze blindelings te volgen. We raden niet aan om blindelings een tool te volgen. Handel zelf is risicovol en prestaties uit het verleden bieden geen garantie voor de toekomst.",
        faq_answer_6: "Voor speciale tijdelijke aanbiedingen die we mogelijk hebben, kun je de kortingscode invoeren tijdens het afrekenen als deze niet automatisch is toegepast. Alle coupons zijn alleen geldig voor de eerste betaling van je abonnement en werken niet tijdens het upgraden of downgraden. Je kunt altijd tot 50% besparen op de totale prijs die je maandelijks zou betalen door jaarlijks te betalen voor onze plannen.",
        faq_answer_7: "Ja, onze Essential & Premium plannen zijn geweldig voor beginners. Elk plan wordt geleverd met veel tutorials en toegang tot onze zeer actieve community waar gebruikers 24/7 ondersteuning kunnen krijgen, strategieën kunnen bespreken en dagelijkse analyses kunnen delen met anderen via LuxAlgo. Ons Ultimate Plan is specifiek ontworpen voor data-gedreven traders die geavanceerd backtesten willen doen.",
        faq_answer_8: "Ja, je kunt je plan op elk moment upgraden, downgraden of verlengen via onze prijspagina wanneer je bent ingelogd. Voor upgrades converteren we de resterende tijd naar een waarde van dagen op je nieuwe plan. Voor downgrades begint je nieuwe plan zodra je huidige plan eindigt. Voor verlengingen van je huidige plan kun je alleen jaarlijkse abonnementen verlengen tot 3 keer, wat meestal populair is tijdens speciale aanbiedingen."

    },
    fr: {
        home: "Home",
        feature: "feature",
        maintenance: "Entretien",
        feedback: "Retour d'information",
        build_websites: "Nous construisons des sites web puissants",
        unlock_power: "Déverrouillez les sites web les plus puissants pour les entreprises avec plus de 100 000 personnes dans le monde entier",
        easy_build: "Facile à construire des sites web puissants",
        modern_websites: "Notre équipe crée des sites web modernes pour votre boutique en ligne, entreprise en quelques jours",
        unlock_access: "Déverrouiller l'accès",
        easy_build_most: "Facile à construire les sites web les plus puissants",
        modern_websites_2: "Notre équipe crée des sites web modernes pour votre boutique en ligne, entreprise en quelques jours",
        unlock_access_2: "Déverrouiller l'accès",
        easy_build_strategies: "Facile à construire des stratégies puissantes",
        modern_websites_3: "Notre équipe crée des sites web modernes pour votre boutique en ligne, entreprise en quelques jours",
        unlock_access_3: "Déverrouiller l'accès",
        basic: "De base",
        basic_price: "$9.99/mois",
        per_site: "Par site par mois",
        simple_design: "Conception et mise en page simples",
        home_page: "Page d'accueil",
        contact_form: "Formulaire de contact",
        responsive_design: "Conception réactive",
        basic_seo: "Configuration SEO de base",
        get_started: "Commencer",
        pro: "Pro",
        pro_price: "$17.99/mois",
        all_basic: "Tout de la version de base",
        advanced_design: "Conception avancée",
        content_management: "Système de gestion de contenu",
        social_media: "Intégration des médias sociaux",
        enhanced_seo: "Recherche de mots_clés SEO améliorée",
        premium: "Premium",
        premium_price: "$25.99/mois",
        all_pro: "Tout de Pro",
        ecommerce: "Fonctionnalité de commerce électronique",
        advanced_analytics: "Analytique avancée",
        blog_setup: "Configuration et intégration de blog",
        custom_graphics: "Graphiques et branding personnalisés",
        website_maintenance: "Maintenance du site web",
        get_site_plan: "Obtenir un plan de site",
        ultra: "Ultra",
        ultra_price: "$32.99/mois",
        all_premium: "Tout de Premium",
        additional_pages: "Pages supplémentaires",
        content_creation: "Création de contenu",
        email_newsletter: "Configuration de la newsletter par e_mail",
        multilingual_support: "Support multilingue",
        ongoing_maintenance: "Maintenance continue",
        custom_development: "Développement personnalisé",
        faq_quastion_1: "Comment ça fonctionne?",
        faq_quastion_2: "Quel plan dois-je choisir?",
        faq_quastion_3: "Quels marchés sont supportés?",
        faq_quastion_4: "Est-ce que ça marche sur MetaTrader 4/5?",
        faq_quastion_5: "Puis-je gagner chaque transaction en utilisant cela?",
        faq_quastion_6: "Comment fonctionnent les réductions?",
        faq_quastion_7: "Est-ce adapté pour les débutants?",
        faq_quastion_8: "Puis-je changer mon plan à tout moment?",
        faq_answer_1: "Une fois que vous vous inscrivez à un plan ci-dessus, vous serez redirigé vers une page qui vous donne un accès instantané. Un lien vous sera également envoyé par e-mail au cas où vous le manqueriez. Vous serez invité à connecter vos comptes TradingView et Discord, qui sont deux plateformes gratuites sur lesquelles nos outils fonctionnent. Nous ne stockons pas les informations de paiement; elles sont cryptées et transmises à Stripe & PayPal pour une manière sécurisée d'acheter des abonnements sur notre site.",
        faq_answer_2: "Le plan Premium est le choix le plus populaire car il fonctionne pour tout style de trading et inclut l'ensemble complet de nos toolkits Signals & Overlays™, Oscillator Matrix™, et Price Action Concepts™. Choisissez le plan Essential pour des fonctionnalités telles que le support/résistance, les lignes de tendance, les motifs et plus encore. Ce plan est également excellent pour les traders sérieux qui veulent accélérer leur analyse avec seulement notre toolkit Price Action Concepts™. Choisissez le plan Ultimate si vous êtes un trader axé sur les données et souhaitez utiliser notre système de backtesting. Il dispose de 3 testeurs qui vous permettent de tester toutes nos toolkits.",
        faq_answer_3: "Tous nos indicateurs fonctionnent sur tous les marchés disponibles sur TradingView, tels que les actions, crypto, forex et matières premières sur toutes les périodes, y compris 1m, 5m, 15m, 1h, 4H, 1D, etc. Les toolkits que nous proposons dans chaque plan peuvent hypothétiquement convenir à n'importe quel style de trading (scalping, swing trading, investissement, etc.) pour trouver des informations techniques.",
        faq_answer_4: "Nos plans payants avec nos toolkits exclusifs fonctionnent uniquement sur TradingView (plateforme de graphiques en ligne gratuite), et vous pouvez trader sur n'importe quelle plateforme en temps réel en fonction de ces graphiques. Nous offrons certains outils gratuits pour MetaTrader 4/5, mais nos toolkits exclusifs fonctionnent spécifiquement sur TradingView.",
        faq_answer_5: "Absolument pas. Il n'existe aucun indicateur, algorithme, système ou stratégie capable de vous donner le pouvoir de prédire les marchés avec une précision garantie. Nous sommes le plus grand fournisseur d'indicateurs (gratuits et payants); cependant, nos outils ne peuvent pas garantir que vous ferez des profits en les suivant aveuglément. Nous ne recommandons pas de suivre aveuglément n'importe quel outil. Le trading lui-même est risqué et les performances passées ne garantissent pas les résultats futurs.",
        faq_answer_6: "Pour les offres spéciales limitées dans le temps que nous pourrions avoir, vous pouvez appliquer le code promo lors du paiement s'il n'est pas déjà automatiquement appliqué. Notez que tous les coupons sont valables uniquement pour le premier paiement de votre abonnement et ne fonctionneront pas lors du processus de mise à niveau ou de rétrogradation. Vous pouvez toujours obtenir jusqu'à 50 % de réduction sur le prix total que vous paieriez mensuellement en choisissant de payer annuellement pour nos plans ci-dessus.",
        faq_answer_7: "Oui, nos plans Essential & Premium sont excellents pour les débutants. Chaque plan comprend de nombreux tutoriels ainsi qu'un accès à notre communauté très active où les utilisateurs peuvent obtenir un support 24/7, discuter des stratégies et effectuer des analyses quotidiennes entre eux en utilisant LuxAlgo. Notre plan Ultimate a été spécialement conçu pour les traders axés sur les données qui souhaitent effectuer des tests plus avancés.",
        faq_answer_8: "Oui, vous pouvez mettre à niveau, rétrograder ou même prolonger votre plan à tout moment en utilisant notre page de tarification une fois connecté. Pour les mises à niveau, nous convertissons le temps restant en une valeur de jours sur votre nouveau plan. Pour les rétrogradations, votre nouveau plan commencera une fois que votre plan actuel se terminera. Pour les prolongations de votre plan actuel, vous ne pouvez prolonger que les abonnements annuels jusqu'à 3 fois, ce qui est généralement populaire lors des ventes spéciales."

    },
    tr: {
        home: "Ev",
        feature: "özellik",
        maintenance: "Bakım",
        feedback: "Geri bildirim",
        build_websites: "Güçlü web siteleri oluşturuyoruz",
        unlock_power: "Dünyada 100.000'den fazla kişiyle işletmeler için en güçlü web sitelerini açın",
        easy_build: "Kolayca güçlü web siteleri oluşturun",
        modern_websites: "Ekibimiz, çevrimiçi mağazanız için modern web sitelerini birkaç gün içinde oluşturuyor",
        unlock_access: "Erişimi aç",
        easy_build_most: "En güçlü web sitelerini kolayca oluşturun",
        modern_websites_2: "Ekibimiz, çevrimiçi mağazanız için modern web sitelerini birkaç gün içinde oluşturuyor",
        unlock_access_2: "Erişimi aç",
        easy_build_strategies: "Kolayca güçlü stratejiler oluşturun",
        modern_websites_3: "Ekibimiz, çevrimiçi mağazanız için modern web sitelerini birkaç gün içinde oluşturuyor",
        unlock_access_3: "Erişimi aç",
        basic: "Temel",
        basic_price: "$9.99/ay",
        per_site: "Site başına aylık",
        simple_design: "Basit Tasarım ve Düzen",
        home_page: "Ana Sayfa",
        contact_form: "İletişim Formu",
        responsive_design: "Duyarlı Tasarım",
        basic_seo: "Temel SEO Ayarı",
        get_started: "Başlamak",
        pro: "Pro",
        pro_price: "$17.99/ay",
        all_basic: "Temel sürümden her şey",
        advanced_design: "Gelişmiş Tasarım",
        content_management: "İçerik Yönetim Sistemi",
        social_media: "Sosyal Medya Entegrasyonu",
        enhanced_seo: "Geliştirilmiş SEO Anahtar Kelime Araştırması",
        premium: "Premium",
        premium_price: "$25.99/ay",
        all_pro: "Pro'dan her şey",
        ecommerce: "E-ticaret İşlevselliği",
        advanced_analytics: "Gelişmiş Analitik",
        blog_setup: "Blog Kurulumu ve Entegrasyonu",
        custom_graphics: "Özel Grafikler ve Markalama",
        website_maintenance: "Web Sitesi Bakımı",
        get_site_plan: "Site Planı Al",
        ultra: "Ultra",
        ultra_price: "$32.99/ay",
        all_premium: "Premium'dan her şey",
        additional_pages: "Ek Sayfalar",
        content_creation: "İçerik Oluşturma",
        email_newsletter: "E-posta Bülteni Kurulumu",
        multilingual_support: "Çok Dilli Destek",
        ongoing_maintenance: "Sürekli Bakım",
        custom_development: "Özel Geliştirme",
        faq_quastion_1: "Nasıl çalışır?",
        faq_quastion_2: "Hangi planı seçmeliyim?",
        faq_quastion_3: "Hangi piyasalar destekleniyor?",
        faq_quastion_4: "MetaTrader 4/5'te çalışır mı?",
        faq_quastion_5: "Bunu kullanarak her ticareti kazanabilir miyim?",
        faq_quastion_6: "İndirimler nasıl çalışır?",
        faq_quastion_7: "Bu, acemiler için uygun mu?",
        faq_quastion_8: "Planımı istediğim zaman değiştirebilir miyim?",
        faq_answer_1: "Yukarıdaki bir plana kaydolduktan sonra, size anında erişim sağlayan bir sayfaya yönlendirilirsiniz. Kaçırmanız durumunda size ayrıca bir bağlantı e-posta ile gönderilecektir. Ücretsiz platformlar olan TradingView ve Discord hesaplarınızı bağlamanız istenir. Ödeme bilgilerini saklamıyoruz; bunlar şifrelenir ve site üzerindeki abonelikleri güvenli bir şekilde satın almak için Stripe ve PayPal’a iletilir.",
        faq_answer_2: "Premium Plan en popüler seçimdir çünkü herhangi bir ticaret stili için çalışır ve Signals & Overlays™, Oscillator Matrix™ ve Price Action Concepts™ toolkitlerinin tam setini içerir. Destek/direnç, trend çizgileri, desenler gibi özellikler için Essential Plan'ı seçin. Bu plan, analizlerini yalnızca Price Action Concepts™ toolkitimiz ile hızlandırmak isteyen ciddi traderlar için de mükemmeldir. Ultimate Plan’ı seçin eğer veriye dayalı bir trader iseniz ve Backtesting System™'imizi kullanmak istiyorsanız. 3 backtester içerir ve tüm toolkitlerimizi geri test edebilmenizi sağlar.",
        faq_answer_3: "Tüm göstergelerimiz, TradingView'de bulunan hisse senetleri, kripto, forex ve emtia gibi herhangi bir piyasada ve 1m, 5m, 15m, 1h, 4H, 1D gibi tüm zaman dilimlerinde çalışır. Her planda sağladığımız toolkitler, teknik analiz bulguları için her tür ticaret stiline (scalping, swing trading, yatırım vb.) uyacak şekilde tasarlanmıştır.",
        faq_answer_4: "Ücretli planlarımız ve yukarıdaki özel toolkitlerimiz sadece TradingView (ücretsiz web tabanlı grafik platformu) üzerinde çalışır ve bu grafiklere dayanarak herhangi bir platformda gerçek zamanlı işlem yapabilirsiniz. MetaTrader 4/5 için bazı ücretsiz araçlar sunuyoruz, ancak özel toolkitlerimiz özellikle TradingView üzerinde çalışır.",
        faq_answer_5: "Kesinlikle hayır. Piyasaları garantili % doğrulukla tahmin etmenizi sağlayacak hiçbir gösterge, algoritma, sistem veya strateji yoktur. Biz en büyük gösterge sağlayıcısıyız (ücretsiz ve ücretli); ancak, araçlarımızı körü körüne takip ederek kar elde edeceğinizi garanti edemeyiz. Hiçbir aracı körü körüne takip etmenizi tavsiye etmiyoruz. Ticaretin kendisi risklidir ve geçmiş performans gelecekteki sonuçları garanti etmez.",
        faq_answer_6: "Sınırlı süreli özel tekliflerimiz olduğunda, ödeme sırasında otomatik olarak uygulanmamışsa kupon kodunu girebilirsiniz. Tüm kuponlar yalnızca aboneliğinizin ilk ödemesi içindir ve yükseltme veya düşürme işlemi sırasında çalışmaz. Yıllık ödeme yaparak yukarıdaki planlarımızda aylık olarak ödeyeceğiniz toplam fiyat üzerinden %50’ye kadar tasarruf edebilirsiniz.",
        faq_answer_7: "Evet, Essential & Premium planlarımız acemiler için harikadır. Her plan, birçok eğitim ve kullanıcıların 7/24 destek alabileceği, stratejileri tartışabileceği ve LuxAlgo kullanarak birbirleriyle günlük analizler yapabileceği oldukça aktif topluluğumuza erişimle birlikte gelir. Ultimate Plan'ımız, daha ileri düzey geri testler yapmak isteyen veri odaklı traderlar için özel olarak tasarlanmıştır.",
        faq_answer_8: "Evet, giriş yaptıktan sonra fiyatlandırma sayfamızı kullanarak planınızı istediğiniz zaman yükseltebilir, düşürebilir veya uzatabilirsiniz. Yükseltmeler için kalan süreyi yeni planınızdaki gün değerine dönüştürüyoruz. Düşürmelerde, yeni planınız mevcut planınızın bitiminden sonra başlar. Mevcut planınızın uzatılması için yalnızca yıllık abonelikleri en fazla 3 kez uzatabilirsiniz, bu genellikle özel satışlar sırasında popülerdir."


    },

    arab: {
        home: "الرئيسية",
        feature: "ميزة",
        maintenance: "الصيانة",
        feedback: "التعليقات",
        build_websites: "نبني مواقع ويب قوية",
        unlock_power: "افتح أقوى مواقع الويب للأعمال التجارية مع أكثر من 100,000 شخص حول العالم",
        easy_build: "بناء مواقع ويب قوية بسهولة",
        modern_websites: "فريقنا يصمم مواقع ويب حديثة لمتجرك الإلكتروني، عملك في غضون أيام",
        unlock_access: "افتح الوصول",
        easy_build_most: "بناء أقوى مواقع الويب بسهولة",
        modern_websites_2: "فريقنا يصمم مواقع ويب حديثة لمتجرك الإلكتروني، عملك في غضون أيام",
        unlock_access_2: "افتح الوصول",
        easy_build_strategies: "بناء استراتيجيات قوية بسهولة",
        modern_websites_3: "فريقنا يصمم مواقع ويب حديثة لمتجرك الإلكتروني، عملك في غضون أيام",
        unlock_access_3: "افتح الوصول",
        basic: "أساسي",
        basic_price: "$9.99/شهر",
        per_site: "لكل موقع شهرياً",
        simple_design: "تصميم وتخطيط بسيط",
        home_page: "الصفحة الرئيسية",
        contact_form: "نموذج الاتصال",
        responsive_design: "تصميم متجاوب",
        basic_seo: "إعدادات SEO الأساسية",
        get_started: "ابدأ الآن",
        pro: "احترافي",
        pro_price: "$17.99/شهر",
        all_basic: "كل شيء من الإصدار الأساسي",
        advanced_design: "تصميم متقدم",
        content_management: "نظام إدارة المحتوى",
        social_media: "دمج وسائل التواصل الاجتماعي",
        enhanced_seo: "البحث المحسن عن الكلمات الرئيسية لـ SEO",
        premium: "مميز",
        premium_price: "$25.99/شهر",
        all_pro: "كل شيء من الإصدار الاحترافي",
        ecommerce: "وظائف التجارة الإلكترونية",
        advanced_analytics: "تحليلات متقدمة",
        blog_setup: "إعداد وتكامل المدونة",
        custom_graphics: "رسومات مخصصة وعلامات تجارية",
        website_maintenance: "صيانة الموقع",
        get_site_plan: "احصل على خطة الموقع",
        ultra: "ألترا",
        ultra_price: "$32.99/شهر",
        all_premium: "كل شيء من الإصدار المميز",
        additional_pages: "صفحات إضافية",
        content_creation: "إنشاء المحتوى",
        email_newsletter: "إعداد النشرة الإخبارية عبر البريد الإلكتروني",
        multilingual_support: "دعم متعدد اللغات",
        ongoing_maintenance: "صيانة مستمرة",
        custom_development: "تطوير مخصص",
        faq_question_1: "كيف يعمل؟",
        faq_question_2: "أي خطة يجب أن أختار؟",
        faq_question_3: "ما هي الأسواق المدعومة؟",
        faq_question_4: "هل يعمل على MetaTrader 4/5؟",
        faq_question_5: "هل يمكنني الفوز في كل صفقة باستخدام هذا؟",
        faq_question_6: "كيف تعمل الخصومات؟",
        faq_question_7: "هل هذا مناسب للمبتدئين؟",
        faq_question_8: "هل يمكنني تغيير خطتي في أي وقت؟",
        faq_answer_1: "بمجرد الاشتراك في خطة أعلاه، سيتم نقلك إلى صفحة تمنحك الوصول الفوري. سيتم أيضًا إرسال رابط إليك عبر البريد الإلكتروني في حال فقدته. سيتم مطالبتك بربط حساباتك على TradingView وDiscord، وكلاهما منصات مجانية تعمل عليها أدواتنا. نحن لا نخزن بيانات الدفع؛ بل يتم تشفيرها وإرسالها إلى Stripe وPayPal لشراء الاشتراكات بأمان على موقعنا.",
        faq_answer_2: "خطة Premium هي الأكثر شهرة لأنها تناسب أي أسلوب تداول وتشمل المجموعة الكاملة من إشاراتنا وأدوات التراكب™، وأدوات مصفوفة المذبذبات™، ومفاهيم حركة السعر™. اختر الخطة الأساسية للحصول على ميزات مثل الدعم/المقاومة، خطوط الاتجاه، الأنماط والمزيد. هذه الخطة أيضًا رائعة للمتداولين الجادين الذين يرغبون في تسريع تحليلهم باستخدام مجموعة مفاهيم حركة السعر™ فقط. اختر خطة Ultimate إذا كنت متداولًا معتمدًا على البيانات وترغب في الاستفادة من نظام الاختبار العكسي™. يحتوي على 3 أدوات اختبار عكسي تتيح لك اختبار كل أدواتنا.",
        faq_answer_3: "جميع مؤشراتنا تعمل على أي سوق متاح على TradingView مثل الأسهم والعملات الرقمية والفوركس والسلع بجميع الأطر الزمنية بما في ذلك 1m, 5m, 15m, 1h, 4H, 1D، إلخ. الأدوات التي نوفرها في كل خطة يمكن أن تتناسب مع أي أسلوب تداول نظريًا (سكالبينج، التداول المتأرجح، الاستثمار، إلخ) للبحث عن رؤى فنية.",
        faq_answer_4: "خططنا المدفوعة مع أدواتنا الحصرية المتاحة أعلاه تعمل فقط على TradingView (منصة رسوم بيانية قائمة على الويب مجانية)، ويمكنك التداول على أي منصة في الوقت الفعلي بناءً على هذه الرسوم البيانية. نحن نوفر بعض الأدوات المجانية لـ MetaTrader 4/5، لكن أدواتنا الحصرية تعمل تحديدًا على TradingView.",
        faq_answer_5: "بالتأكيد لا. لا يوجد مؤشر، أو خوارزمية، أو نظام، أو استراتيجية تتيح لك التنبؤ بالأسواق بدقة مضمونة. نحن أكبر مزود للمؤشرات (مجانية ومدفوعة)؛ ومع ذلك، لا يمكن لأدواتنا أن تضمن لك الربح بمجرد اتباعها بشكل أعمى. لا نوصي باتباع أي أداة بشكل أعمى. التداول بحد ذاته محفوف بالمخاطر، وأداء الماضي لا يضمن النتائج المستقبلية.",
        faq_answer_6: "بالنسبة للعروض الخاصة المحدودة، يمكنك تطبيق رمز القسيمة أثناء الدفع إذا لم يتم تطبيقه تلقائيًا. لاحظ أن جميع القسائم تكون للدفع الأول فقط من اشتراكك ولن تعمل أثناء عملية الترقية أو الخفض. يمكنك دائمًا الحصول على خصم يصل إلى 50٪ من السعر الإجمالي الذي ستدفعه شهريًا عن طريق اختيار الدفع السنوي على الخطط أعلاه.",
        faq_answer_7: "نعم، خططنا الأساسية وPremium رائعة للمبتدئين. تأتي كل خطة مع العديد من الدروس وكذلك الوصول إلى مجتمعنا النشط للغاية حيث يمكن للمستخدمين الحصول على دعم على مدار الساعة، ومناقشة الاستراتيجيات، ومتابعة التحليل اليومي بين بعضهم البعض باستخدام LuxAlgo. تم تصميم خطة Ultimate خصيصًا للمتداولين المعتمدين على البيانات الذين يرغبون في إجراء اختبارات عكسية أكثر تقدمًا.",
        faq_answer_8: "نعم، يمكنك الترقية أو الخفض أو حتى تمديد خطتك في أي وقت باستخدام صفحة التسعير بمجرد تسجيل الدخول. بالنسبة للترقيات، نقوم بتحويل الوقت المتبقي إلى قيمة بالأيام على خطتك الجديدة. بالنسبة للتخفيضات، ستبدأ خطتك الجديدة بمجرد انتهاء خطتك الحالية. بالنسبة لتمديد خطتك الحالية، يمكنك فقط تمديد الاشتراكات السنوية وحتى 3 مرات، وهو ما يكون شائعًا عادةً خلال العروض الخاصة."


    },
    chinees: {
        home: "首页",
        feature: "功能",
        maintenance: "维护",
        feedback: "反馈",
        build_websites: "我们构建强大的网站",
        unlock_power: "与全球超过100,000人一起解锁最强大的企业网站",
        easy_build: "轻松构建强大的网站",
        modern_websites: "我们的团队在几天内为您的网店和企业创建现代网站",
        unlock_access: "解锁访问",
        easy_build_most: "轻松构建最强大的网站",
        modern_websites_2: "我们的团队在几天内为您的网店和企业创建现代网站",
        unlock_access_2: "解锁访问",
        easy_build_strategies: "轻松构建强大的策略",
        modern_websites_3: "我们的团队在几天内为您的网店和企业创建现代网站",
        unlock_access_3: "解锁访问",
        basic: "基础版",
        basic_price: "$9.99/月",
        per_site: "每站每月",
        simple_design: "简单的设计和布局",
        home_page: "主页",
        contact_form: "联系表单",
        responsive_design: "响应式设计",
        basic_seo: "基本SEO设置",
        get_started: "开始使用",
        pro: "专业版",
        pro_price: "$17.99/月",
        all_basic: "包括基础版的所有功能",
        advanced_design: "高级设计",
        content_management: "内容管理系统",
        social_media: "社交媒体集成",
        enhanced_seo: "增强的SEO关键字搜索",
        premium: "高级版",
        premium_price: "$25.99/月",
        all_pro: "包括专业版的所有功能",
        ecommerce: "电子商务功能",
        advanced_analytics: "高级分析",
        blog_setup: "博客设置和集成",
        custom_graphics: "定制图形和品牌",
        website_maintenance: "网站维护",
        get_site_plan: "获取站点计划",
        ultra: "终极版",
        ultra_price: "$32.99/月",
        all_premium: "包括高级版的所有功能",
        additional_pages: "额外页面",
        content_creation: "内容创建",
        email_newsletter: "电子邮件通讯设置",
        multilingual_support: "多语言支持",
        ongoing_maintenance: "持续维护",
        custom_development: "定制开发",
        faq_quastion_1: "它是如何工作的？",
        faq_quastion_2: "我应该选择哪个计划？",
        faq_quastion_3: "支持哪些市场？",
        faq_quastion_4: "它可以在MetaTrader 4/5上工作吗？",
        faq_quastion_5: "使用这个我可以赢得每一笔交易吗？",
        faq_quastion_6: "折扣如何运作？",
        faq_quastion_7: "这对初学者友好吗？",
        faq_quastion_8: "我可以随时更改我的计划吗？",
        faq_answer_1: "一旦您注册了上面的某个计划，您将被带到一个页面，提供即时访问。 如果您错过了，还会将链接通过电子邮件发送给您。您需要连接您的TradingView和Discord帐户，这两个都是我们的工具运行的免费平台。我们不存储支付凭证，它们经过加密并传递给Stripe和PayPal，以确保在我们的网站上安全购买订阅。",
        faq_answer_2: "高级计划是最受欢迎的选择，因为它适用于任何交易风格，并包括我们Signals & Overlays™、Oscillator Matrix™和Price Action Concepts™工具包的完整集。选择基本计划以获得支持/阻力、趋势线、模式等功能。该计划也非常适合希望使用我们Price Action Concepts™工具包加快分析的严肃交易者。如果您是一个数据驱动的交易者，希望利用我们的回测系统™，请选择终极计划。它有3个回测器，可以让您回测我们的所有工具包。",
        faq_answer_3: "我们的所有指标都适用于TradingView上提供的任何市场，如股票、加密货币、外汇和商品，在所有时间框架（包括1分钟、5分钟、15分钟、1小时、4小时、1天等）上运行。我们在每个计划中提供的工具包可以适应任何交易风格（剥头皮、波段交易、投资等），以寻找技术洞察。",
        faq_answer_4: "我们的付费计划和上述独家工具包仅适用于TradingView（免费基于网页的图表平台），您可以基于这些图表在任何平台上实时交易。我们确实为MetaTrader 4/5提供了一些免费工具，但是我们的独家工具包专门在TradingView上运行。",
        faq_answer_5: "绝对不是。没有任何指标、算法、系统或策略可以赋予您以保证的准确率预测市场的能力。我们是最大的指标提供商（免费和付费）；但是，我们的工具不能保证您通过盲目跟随它们而获利。我们不建议盲目跟随任何工具。交易本身是有风险的，过去的表现不能保证未来的结果。",
        faq_answer_6: "对于我们可能提供的特别限时优惠，如果优惠码未自动应用，您可以在结账时输入。请注意，所有优惠码仅适用于订阅的首次付款，不适用于升级或降级过程中。通过选择上面计划中的年付，您可以在每月支付的总价格上节省最多50％。",
        faq_answer_7: "是的，我们的基本和高级计划对初学者来说非常友好。每个计划都附带许多教程，以及访问我们高度活跃的社区，用户可以获得24/7支持、讨论策略并通过LuxAlgo进行每日分析。我们的终极计划是专为希望进行更高级回测的数据驱动交易者设计的。",
        faq_answer_8: "是的，登录后，您可以通过我们的定价页面随时升级、降级或延长您的计划。对于升级，我们将剩余时间转换为您新计划中的天数价值。对于降级，您的新计划将在当前计划结束后开始。对于当前计划的延长，您只能延长年度订阅最多3次，这通常在特别促销期间很受欢迎。"


    },
    spanish: {
        home: "Inicio",
        feature: "Característica",
        maintenance: "Mantenimiento",
        feedback: "Comentarios",
        build_websites: "Construimos sitios web poderosos",
        unlock_power: "Desbloquea los sitios web más poderosos para empresas con más de 100,000 personas a nivel mundial",
        easy_build: "Construcción fácil de sitios web poderosos",
        modern_websites: "Nuestro equipo crea sitios web modernos para tu tienda en línea, negocio en pocos días",
        unlock_access: "Desbloquear acceso",
        easy_build_most: "Construcción fácil de los sitios web más poderosos",
        modern_websites_2: "Nuestro equipo crea sitios web modernos para tu tienda en línea, negocio en pocos días",
        unlock_access_2: "Desbloquear acceso",
        easy_build_strategies: "Construcción fácil de estrategias poderosas",
        modern_websites_3: "Nuestro equipo crea sitios web modernos para tu tienda en línea, negocio en pocos días",
        unlock_access_3: "Desbloquear acceso",
        basic: "Básico",
        basic_price: "$9.99/mes",
        per_site: "Por sitio por mes",
        simple_design: "Diseño y maquetación simples",
        home_page: "Página de inicio",
        contact_form: "Formulario de contacto",
        responsive_design: "Diseño responsivo",
        basic_seo: "Configuración básica de SEO",
        get_started: "Comenzar",
        pro: "Pro",
        pro_price: "$17.99/mes",
        all_basic: "Todo de la versión básica",
        advanced_design: "Diseño avanzado",
        content_management: "Sistema de gestión de contenido",
        social_media: "Integración de redes sociales",
        enhanced_seo: "Búsqueda de palabras clave SEO mejorada",
        premium: "Premium",
        premium_price: "$25.99/mes",
        all_pro: "Todo de Pro",
        ecommerce: "Funcionalidad de comercio electrónico",
        advanced_analytics: "Analítica avanzada",
        blog_setup: "Configuración e integración de blogs",
        custom_graphics: "Gráficos personalizados y branding",
        website_maintenance: "Mantenimiento del sitio web",
        get_site_plan: "Obtener plan de sitio",
        ultra: "Ultra",
        ultra_price: "$32.99/mes",
        all_premium: "Todo de Premium",
        additional_pages: "Páginas adicionales",
        content_creation: "Creación de contenido",
        email_newsletter: "Configuración de boletines por correo electrónico",
        multilingual_support: "Soporte multilingüe",
        ongoing_maintenance: "Mantenimiento continuo",
        custom_development: "Desarrollo personalizado",
        faq_quastion_1: "¿Cómo funciona?",
        faq_quastion_2: "¿Qué plan debería elegir?",
        faq_quastion_3: "¿Qué mercados son compatibles?",
        faq_quastion_4: "¿Funciona en MetaTrader 4/5?",
        faq_quastion_5: "¿Puedo ganar todas las operaciones con esto?",
        faq_quastion_6: "¿Cómo funcionan los descuentos?",
        faq_quastion_7: "¿Es apto para principiantes?",
        faq_quastion_8: "¿Puedo cambiar mi plan en cualquier momento?",
        faq_answer_1: "Una vez que te registres en un plan, serás llevado a una página que te dará acceso instantáneo. También se te enviará un enlace por correo electrónico en caso de que lo pierdas. Se te pedirá que conectes tus cuentas de TradingView y Discord, ambas son plataformas gratuitas en las que funcionan nuestras herramientas. No almacenamos credenciales de pago; están encriptadas y se envían a Stripe y PayPal para una compra segura de suscripciones en nuestro sitio.",
        faq_answer_2: "El Plan Premium es la opción más popular, ya que funciona para cualquier estilo de trading e incluye el conjunto completo de nuestras herramientas Signals & Overlays™, Oscillator Matrix™, y Price Action Concepts™. Elige el Plan Esencial para características como soporte/resistencia, líneas de tendencia, patrones y más. Este plan también es ideal para traders serios que quieren acelerar su análisis solo con nuestra herramienta Price Action Concepts™. Elige el Plan Ultimate si eres un trader impulsado por los datos que busca utilizar nuestro Sistema de Pruebas Retrospectivas™. Tiene 3 probadores de retrocesos que te permiten probar todos nuestros conjuntos de herramientas.",
        faq_answer_3: "Todos nuestros indicadores funcionan en cualquier mercado disponible en TradingView, como acciones, criptomonedas, forex y materias primas en todos los marcos de tiempo, incluidos 1m, 5m, 15m, 1h, 4H, 1D, etc. Los conjuntos de herramientas que proporcionamos en cada plan pueden encajar hipotéticamente en cualquier estilo de trading (scalping, swing trading, inversión, etc.) para encontrar perspectivas técnicas.",
        faq_answer_4: "Nuestros planes de pago con nuestras herramientas exclusivas disponibles solo funcionan en TradingView (plataforma de gráficos basada en la web gratuita), y puedes operar en cualquier plataforma en tiempo real basándote en esos gráficos. Ofrecemos algunas herramientas gratuitas para MetaTrader 4/5; sin embargo, nuestras herramientas exclusivas funcionan específicamente en TradingView.",
        faq_answer_5: "Absolutamente no. No existe ningún indicador, algoritmo, sistema o estrategia que te dé el poder de predecir los mercados con un porcentaje de precisión garantizado. Somos el mayor proveedor de indicadores (gratuitos y de pago); sin embargo, nuestras herramientas no pueden garantizar que obtengas beneficios siguiendo ciegamente. No recomendamos seguir ninguna herramienta ciegamente. El trading en sí mismo es arriesgado y el rendimiento pasado no garantiza resultados futuros.",
        faq_answer_6: "Para ofertas especiales de tiempo limitado que podamos tener, puedes aplicar el código de cupón durante el pago si no se aplica automáticamente. Ten en cuenta que todos los cupones son solo para el primer pago de tu suscripción y no funcionarán durante el proceso de actualización o degradación. Siempre puedes obtener hasta un 50% de descuento sobre el precio total que pagarías mensualmente eligiendo pagar anualmente en nuestros planes anteriores.",
        faq_answer_7: "Sí, nuestros planes Esencial y Premium son excelentes para principiantes. Cada plan viene con muchos tutoriales, así como acceso a nuestra comunidad altamente activa donde los usuarios pueden obtener soporte 24/7, discutir estrategias y realizar análisis diarios entre ellos usando LuxAlgo. Nuestro Plan Ultimate fue diseñado específicamente para traders basados en datos que desean realizar pruebas más avanzadas.",
        faq_answer_8: "Sí, puedes actualizar, degradar o incluso extender tu plan en cualquier momento utilizando nuestra página de precios una vez que hayas iniciado sesión. Para las actualizaciones, convertimos el tiempo restante en un valor de días en tu nuevo plan. Para las degradaciones, tu nuevo plan comenzará una vez que termine tu plan actual. Para las extensiones de tu plan actual, solo puedes extender suscripciones anuales hasta 3 veces, lo cual es popular durante las ventas especiales."


    },
    russia: {
        home: "Главная",
        feature: "Функции",
        maintenance: "Обслуживание",
        feedback: "Отзывы",
        build_websites: "Мы создаем мощные сайты",
        unlock_power: "Разблокируйте самые мощные сайты для бизнеса с более чем 100,000 человек по всему миру",
        easy_build: "Легко создавать мощные сайты",
        modern_websites: "Наша команда создает современные сайты для вашего интернет-магазина и бизнеса за несколько дней",
        unlock_access: "Разблокировать доступ",
        easy_build_most: "Легко создавать самые мощные сайты",
        modern_websites_2: "Наша команда создает современные сайты для вашего интернет-магазина и бизнеса за несколько дней",
        unlock_access_2: "Разблокировать доступ",
        easy_build_strategies: "Легко создавать мощные стратегии",
        modern_websites_3: "Наша команда создает современные сайты для вашего интернет-магазина и бизнеса за несколько дней",
        unlock_access_3: "Разблокировать доступ",
        basic: "Базовый",
        basic_price: "$9.99/месяц",
        per_site: "За сайт в месяц",
        simple_design: "Простой дизайн и макет",
        home_page: "Главная страница",
        contact_form: "Контактная форма",
        responsive_design: "Адаптивный дизайн",
        basic_seo: "Основная настройка SEO",
        get_started: "Начать",
        pro: "Про",
        pro_price: "$17.99/месяц",
        all_basic: "Все из базовой версии",
        advanced_design: "Продвинутый дизайн",
        content_management: "Система управления контентом",
        social_media: "Интеграция социальных сетей",
        enhanced_seo: "Улучшенный поиск ключевых слов SEO",
        premium: "Премиум",
        premium_price: "$25.99/месяц",
        all_pro: "Все из версии Про",
        ecommerce: "Функциональность электронной коммерции",
        advanced_analytics: "Продвинутый анализ",
        blog_setup: "Настройка и интеграция блога",
        custom_graphics: "Индивидуальная графика и брендинг",
        website_maintenance: "Обслуживание сайта",
        get_site_plan: "Получить план сайта",
        ultra: "Ультра",
        ultra_price: "$32.99/месяц",
        all_premium: "Все из версии Премиум",
        additional_pages: "Дополнительные страницы",
        content_creation: "Создание контента",
        email_newsletter: "Настройка электронных новостных рассылок",
        multilingual_support: "Поддержка нескольких языков",
        ongoing_maintenance: "Постоянное обслуживание",
        custom_development: "Индивидуальная разработка",
        faq_question_1: "Как это работает?",
        faq_question_2: "Какой план мне выбрать?",
        faq_question_3: "Какие рынки поддерживаются?",
        faq_question_4: "Работает ли это на MetaTrader 4/5?",
        faq_question_5: "Могу ли я выиграть каждую сделку, используя это?",
        faq_question_6: "Как работают скидки?",
        faq_question_7: "Подходит ли это для начинающих?",
        faq_question_8: "Могу ли я изменить свой план в любое время?",
        faq_answer_1: "После того, как вы подпишетесь на один из планов выше, вас перенаправят на страницу с мгновенным доступом. Ссылка также будет отправлена на вашу электронную почту на случай, если вы ее пропустили. Вам будет предложено подключить свои аккаунты TradingView и Discord, которые являются бесплатными платформами, на которых работают наши инструменты. Мы не храним данные платежей; они зашифрованы и передаются в Stripe и PayPal для безопасной и надежной покупки подписок на нашем сайте.",
        faq_answer_2: "План Premium является самым популярным выбором, так как он подходит для любого стиля торговли и включает полный набор наших инструментов Signals & Overlays™, Oscillator Matrix™, и Price Action Concepts™. Выберите план Essential для таких функций, как поддержка/сопротивление, линии тренда, шаблоны и многое другое. Этот план также отлично подходит для серьезных трейдеров, которые хотят ускорить анализ с помощью только нашего инструментария Price Action Concepts™. Выберите план Ultimate, если вы трейдер, ориентированный на данные, и хотите использовать нашу систему бэктестинга™. В нем есть 3 инструмента бэктестинга, которые позволяют тестировать все наши инструменты.",
        faq_answer_3: "Все наши индикаторы работают на любом рынке, доступном на TradingView, таких как акции, криптовалюты, форекс и товары, на всех таймфреймах, включая 1m, 5m, 15m, 1h, 4H, 1D и т.д. Инструментарий, предоставляемый на каждом плане, гипотетически может подойти для любого стиля торговли (скальпинг, свинг-трейдинг, инвестирование и т.д.) для поиска технических данных.",
        faq_answer_4: "Наши платные планы с эксклюзивными наборами инструментов, доступными выше, работают только на TradingView (бесплатная платформа для веб-чартов), и вы можете торговать на любой платформе в реальном времени, основываясь на этих графиках. У нас есть некоторые бесплатные инструменты для MetaTrader 4/5, однако наши эксклюзивные инструменты работают исключительно на TradingView.",
        faq_answer_5: "Абсолютно нет. Нет ни одного индикатора, алгоритма, системы или стратегии, которая могла бы предсказать рынки с гарантированной точностью. Мы являемся крупнейшим поставщиком индикаторов (бесплатных и платных); однако, наши инструменты не могут гарантировать вам прибыль при слепом следовании за ними. Мы не рекомендуем слепо следовать любым инструментам. Сам процесс торговли рискован, а прошлые результаты не гарантируют будущих успехов.",
        faq_answer_6: "Для специальных ограниченных предложений вы можете применить купон во время оформления заказа, если он еще не был автоматически применен. Обратите внимание, что все купоны действительны только для первого платежа по вашей подписке и не будут работать при повышении или понижении тарифа. Вы всегда можете получить скидку до 50% от общей ежемесячной суммы, выбрав оплату за год вперед по планам, перечисленным выше.",
        faq_answer_7: "Да, наши планы Essential и Premium отлично подходят для начинающих. Каждый план включает множество учебных материалов, а также доступ к нашему активно работающему сообществу, где пользователи могут получить поддержку 24/7, обсуждать стратегии и проводить ежедневный анализ вместе, используя LuxAlgo. Наш план Ultimate был специально разработан для трейдеров, ориентированных на данные, которые хотят проводить более сложное тестирование стратегий.",
        faq_answer_8: "Да, вы можете повысить, понизить или даже продлить свой план в любое время, используя страницу тарифов после входа в систему. При повышении тарифа мы конвертируем оставшееся время в количество дней по вашему новому плану. При понижении новый план начнется после окончания текущего. Для продления текущего плана вы можете продлить только годовые подписки и не более чем на 3 раза, что обычно популярно во время специальных распродаж."


    },
    korea:{
       
            home: "홈",
            feature: "기능",
            maintenance: "유지 관리",
            feedback: "피드백",
            build_websites: "우리는 강력한 웹사이트를 만듭니다",
            unlock_power: "전 세계 100,000명 이상의 사람들과 함께 가장 강력한 웹사이트를 비즈니스에 활용하세요",
            easy_build: "쉽게 강력한 웹사이트를 구축하세요",
            modern_websites: "우리 팀은 당신의 웹숍, 비즈니스를 위한 현대적인 웹사이트를 며칠 내로 만듭니다",
            unlock_access: "액세스 잠금 해제",
            easy_build_most: "가장 강력한 웹사이트를 쉽게 구축하세요",
            modern_websites_2: "우리 팀은 당신의 웹숍, 비즈니스를 위한 현대적인 웹사이트를 며칠 내로 만듭니다",
            unlock_access_2: "액세스 잠금 해제",
            easy_build_strategies: "쉽게 강력한 전략을 구축하세요",
            modern_websites_3: "우리 팀은 당신의 웹숍, 비즈니스를 위한 현대적인 웹사이트를 며칠 내로 만듭니다",
            unlock_access_3: "액세스 잠금 해제",
            basic: "기본",
            basic_price: "$9.99/월",
            per_site: "월당",
            simple_design: "단순한 디자인 및 레이아웃",
            home_page: "홈페이지",
            contact_form: "문의 양식",
            responsive_design: "반응형 디자인",
            basic_seo: "기본 SEO 설정",
            get_started: "시작하기",
            pro: "프로",
            pro_price: "$17.99/월",
            all_basic: "기본 버전의 모든 기능 포함",
            advanced_design: "고급 디자인",
            content_management: "콘텐츠 관리 시스템",
            social_media: "소셜 미디어 통합",
            enhanced_seo: "향상된 SEO 키워드 검색",
            premium: "프리미엄",
            premium_price: "$25.99/월",
            all_pro: "프로 버전의 모든 기능 포함",
            ecommerce: "전자 상거래 기능",
            advanced_analytics: "고급 분석",
            blog_setup: "블로그 설정 및 통합",
            custom_graphics: "맞춤형 그래픽 및 브랜딩",
            website_maintenance: "웹사이트 유지 관리",
            get_site_plan: "사이트 계획 얻기",
            ultra: "울트라",
            ultra_price: "$32.99/월",
            all_premium: "프리미엄 버전의 모든 기능 포함",
            additional_pages: "추가 페이지",
            content_creation: "콘텐츠 제작",
            email_newsletter: "이메일 뉴스레터 설정",
            multilingual_support: "다국어 지원",
            ongoing_maintenance: "지속적인 유지 관리",
            custom_development: "맞춤 개발",
            faq_quastion_1: "작동 방식은 어떻게 되나요?",
            faq_quastion_2: "어떤 플랜을 선택해야 하나요?",
            faq_quastion_3: "어떤 시장이 지원되나요?",
            faq_quastion_4: "MetaTrader 4/5에서도 작동하나요?",
            faq_quastion_5: "이것으로 모든 거래에서 승리할 수 있나요?",
            faq_quastion_6: "할인은 어떻게 작동하나요?",
            faq_quastion_7: "초보자에게 친숙한가요?",
            faq_quastion_8: "언제든지 플랜을 변경할 수 있나요?",
            faq_answer_1: "위의 플랜에 가입하면 즉시 액세스할 수 있는 페이지로 이동합니다. 놓친 경우 이메일로 링크가 발송됩니다. 무료 플랫폼인 TradingView 및 Discord 계정을 연결해야 하며, 우리의 도구는 이들 플랫폼에서 작동합니다. 우리는 결제 정보를 저장하지 않으며, 결제 정보는 암호화되어 Stripe 및 PayPal에 안전하게 전달됩니다.",
            faq_answer_2: "프리미엄 플랜은 다양한 거래 스타일에 적합하며, 모든 신호 및 오버레이 도구 세트, 오실레이터 매트릭스, 가격 행동 개념 도구 키트를 포함하기 때문에 가장 인기가 많습니다. Essential 플랜은 지원/저항, 트렌드 라인, 패턴 등 기능을 원하는 진지한 트레이더에게 적합합니다. Ultimate 플랜은 데이터 기반의 트레이더를 위해 백테스팅 시스템을 사용할 수 있는 플랜입니다.",
            faq_answer_3: "우리의 모든 지표는 TradingView에서 제공되는 모든 시장(주식, 암호화폐, 외환, 상품)에서 모든 시간대(1분, 5분, 15분, 1시간 등)에서 작동합니다. 제공되는 도구 키트는 스캘핑, 스윙 트레이딩, 투자 등 다양한 거래 스타일에 맞출 수 있습니다.",
            faq_answer_4: "위의 독점 도구 키트가 포함된 유료 플랜은 TradingView에서만 작동합니다. 우리는 MetaTrader 4/5용 일부 무료 도구도 제공하지만, 독점 도구 키트는 TradingView에서만 작동합니다.",
            faq_answer_5: "절대 아닙니다. 시장을 예측하는 100% 정확한 지표, 알고리즘, 시스템 또는 전략은 존재하지 않습니다. 우리의 도구는 큰 도움이 되지만, 그것을 맹목적으로 따르지 말라고 권장합니다. 거래는 위험하며, 과거 성과가 미래 결과를 보장하지 않습니다.",
            faq_answer_6: "한정된 특별 할인은 결제 시 쿠폰 코드를 적용할 수 있습니다. 모든 쿠폰은 첫 결제에만 적용되며, 플랜 업그레이드나 다운그레이드 시 적용되지 않습니다. 연간 결제 시 최대 50% 할인을 받을 수 있습니다.",
            faq_answer_7: "예, Essential 및 Premium 플랜은 초보자에게 적합합니다. 모든 플랜에는 튜토리얼과 활발한 커뮤니티에 접근할 수 있으며, 24시간 지원을 받을 수 있습니다. Ultimate 플랜은 백테스팅을 원하는 데이터 기반의 트레이더를 위해 설계되었습니다.",
            faq_answer_8: "예, 언제든지 플랜을 업그레이드, 다운그레이드 또는 연장할 수 있습니다. 업그레이드의 경우 남은 기간은 새 플랜의 일수로 변환됩니다. 다운그레이드의 경우 현재 플랜이 끝날 때 새 플랜이 시작됩니다. 연장은 연간 구독만 가능하며, 최대 3번까지 가능합니다."
          
          
    },
};


function translatePage(language) {
    const elements = document.querySelectorAll('[data-translate-key]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate-key');
        if (translations[language][key]) {
            element.innerText = translations[language][key];
        }
    });
}